# Generated by Django 5.2.8 on 2026-01-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('preview', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=150)),
            ],
        ),
    ]
