# Generated by Django 5.2.8 on 2026-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_tag_post_author_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
