# Generated by Django 5.2.8 on 2026-01-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug_author',
            field=models.SlugField(blank=True),
        ),
    ]
