# Generated by Django 5.2.8 on 2026-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_slug_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about_me',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug_author',
            field=models.SlugField(unique=True),
        ),
    ]
